# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.


# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:/usr/local/bin:$PATH:/$HOME/.cargo/bin

# Path to your oh-my-zsh installation.
export ZSH="/home/fuscoyu/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""

plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# To customize environment variable
[[ ! -f ~/.env.sh ]] || source ~/.env.sh

source ~/.zplug/init.zsh

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh
zplug "plugins/copypath", from:oh-my-zsh
zplug "plugins/copyfile", from:oh-my-zsh
zplug "plugins/dirhistory", from:oh-my-zsh
zplug "plugins/jsontools", from:oh-my-zsh
zplug "plugins/history", from:oh-my-zsh
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug romkatv/powerlevel10k, as:theme, depth:1

# Then, source plugins and add commands to $PATH
zplug load

# tmux 
# if [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
if [[ -z "$TMUX" ]]; then
  tmux attach-session -t fuscoyu || tmux new-session -s fuscoyu
fi

# trash-cli
alias rm=trash-put

alias vi=nvim
alias vim=nvim

alias cdgo='cd ~/github/self/learning_go'

alias cdk='cd ~/work/kolla/kolla-ansible'
alias cdi='cd ~/work/kolla/installer'
alias cdn='cd ~/work/openstack/nova'
alias cdc='cd ~/work/openstack/cyborg'
alias cdb='cd ~/work/build/'

alias run-python="when-changed -r -v -1 . python3 "
alias run-go="when-changed -r -v -1 . go run "

export http_proxy=http://192.168.1.197:10809
export https_proxy=http://192.168.1.197:10809

export PATH=$PATH:/usr/local/bin:/usr/go/bin
export GOPATH=/home/fuscoyu/go
